# R for travis: https://docs.travis-ci.com/user/languages/r
# tic https://ropenscilabs.github.io/tic/

before_install: 
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm &&
    export PATH="/usr/local/opt/llvm/bin:$PATH" &&
    export LDFLAGS="-L/usr/local/opt/llvm/lib" &&
    export CFLAGS="-I/usr/local/opt/llvm/include" &&
    export CXXFLAGS="-I/usr/local/opt/llvm/include"; fi
  - R -q -e 'install.packages("remotes"); remotes::install_github("bnosac-dev/tic"); tic::before_install()'
install: R -q -e 'tic::install()'
after_install: R -q -e 'tic::after_install()'
before_script: R -q -e 'tic::before_script()'
script: R -q -e 'tic::script()'
after_success: R -q -e 'tic::after_success()'
after_failure: R -q -e 'tic::after_failure()'
before_deploy: R -q -e 'tic::before_deploy()'
deploy:
  provider: script
  script: R -q -e 'tic::deploy()'
  on:
    all_branches: true
after_deploy: R -q -e 'tic::after_deploy()'
after_script: R -q -e 'tic::after_script()'

##
## Custom parts:
##
language: r
latex: true

matrix:
  include:
    - os: linux
      dist: xenial
      r: oldrel
    - os: linux
      dist: xenial
      r: release
    - os: linux
      dist: trusty 
      r: release
    - os: linux
      dist: precise 
      r: release
    - os: osx
      r: oldrel
    - os: osx
      r: release

brew_packages: 
  - libgit2
  - openssl
  - imagemagick
  - gs

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:opencpu/imagemagick'
    packages:
      - libgit2-dev
      - libssl-dev
      - libmagick++-dev
      - librsvg2-dev
      - libwebp-dev
      - libfftw3-dev

notifications:
  email:
    on_success: change
    on_failure: change

services:
